part of '../../flutter_artist.dart';

class BlockControlFAB extends BlockControl {
  BlockControlFAB({
    super.key,
    required super.currentStackTrace,
    required super.ownerClassInstance,
    required super.block,
    required super.actionType,
    super.navigate,
    //
    String? tooltip,
    Color? foregroundColor,
    Color? backgroundColor,
    Color? focusColor,
    Color? hoverColor,
    Color? splashColor,
    Object? heroTag,
    double? elevation,
    double? focusElevation,
    double? hoverElevation,
    double? highlightElevation,
    double? disabledElevation,
    required void Function()? onPressed,
    MouseCursor? mouseCursor,
    bool mini = false,
    ShapeBorder? shape,
    Clip clipBehavior = Clip.none,
    FocusNode? focusNode,
    bool autofocus = false,
    MaterialTapTargetSize? materialTapTargetSize,
    bool isExtended = false,
    bool? enableFeedback,
  }) : super(
          build: (VoidCallback? onPressed) {
            return FloatingActionButton(
              tooltip: tooltip,
              foregroundColor: foregroundColor,
              backgroundColor: backgroundColor,
              focusColor: focusColor,
              hoverColor: hoverColor,
              splashColor: splashColor,
              heroTag: heroTag,
              elevation: elevation,
              focusElevation: focusElevation,
              hoverElevation: hoverElevation,
              highlightElevation: highlightElevation,
              disabledElevation: disabledElevation,
              onPressed: onPressed,
              mouseCursor: mouseCursor,
              mini: mini,
              shape: shape,
              clipBehavior: clipBehavior,
              focusNode: focusNode,
              autofocus: autofocus,
              materialTapTargetSize: materialTapTargetSize,
              isExtended: isExtended,
              enableFeedback: enableFeedback,
            );
          },
        );

  BlockControlFAB.extended({
    super.key,
    required super.currentStackTrace,
    required super.ownerClassInstance,
    required super.block,
    required super.actionType,
    super.navigate,
    //
    Widget? icon,
    required Widget label,
    String? tooltip,
    Color? foregroundColor,
    Color? backgroundColor,
    Color? focusColor,
    Color? hoverColor,
    Color? splashColor,
    Object? heroTag,
    double? elevation,
    double? focusElevation,
    double? hoverElevation,
    double? highlightElevation,
    double? disabledElevation,
    required void Function()? onPressed,
    MouseCursor? mouseCursor,
    ShapeBorder? shape,
    Clip clipBehavior = Clip.none,
    FocusNode? focusNode,
    bool autofocus = false,
    MaterialTapTargetSize? materialTapTargetSize,
    bool isExtended = false,
    bool? enableFeedback,
    EdgeInsetsGeometry? extendedPadding,
    TextStyle? extendedTextStyle,
  }) : super(
          build: (VoidCallback? onPressed) {
            return FloatingActionButton.extended(
              tooltip: tooltip,
              foregroundColor: foregroundColor,
              backgroundColor: backgroundColor,
              focusColor: focusColor,
              hoverColor: hoverColor,
              splashColor: splashColor,
              heroTag: heroTag,
              elevation: elevation,
              focusElevation: focusElevation,
              hoverElevation: hoverElevation,
              highlightElevation: highlightElevation,
              disabledElevation: disabledElevation,
              onPressed: onPressed,
              mouseCursor: mouseCursor,
              shape: shape,
              clipBehavior: clipBehavior,
              focusNode: focusNode,
              autofocus: autofocus,
              materialTapTargetSize: materialTapTargetSize,
              isExtended: isExtended,
              enableFeedback: enableFeedback,
              icon: icon,
              label: label,
              extendedPadding: extendedPadding,
              extendedTextStyle: extendedTextStyle,
            );
          },
        );

  BlockControlFAB.large({
    super.key,
    required super.currentStackTrace,
    required super.ownerClassInstance,
    required super.block,
    required super.actionType,
    super.navigate,
    //
    String? tooltip,
    Color? foregroundColor,
    Color? backgroundColor,
    Color? focusColor,
    Color? hoverColor,
    Color? splashColor,
    Object? heroTag,
    double? elevation,
    double? focusElevation,
    double? hoverElevation,
    double? highlightElevation,
    double? disabledElevation,
    required void Function()? onPressed,
    MouseCursor? mouseCursor,
    bool mini = false,
    ShapeBorder? shape,
    Clip clipBehavior = Clip.none,
    FocusNode? focusNode,
    bool autofocus = false,
    MaterialTapTargetSize? materialTapTargetSize,
    bool isExtended = false,
    bool? enableFeedback,
  }) : super(
          build: (VoidCallback? onPressed) {
            return FloatingActionButton.large(
              tooltip: tooltip,
              foregroundColor: foregroundColor,
              backgroundColor: backgroundColor,
              focusColor: focusColor,
              hoverColor: hoverColor,
              splashColor: splashColor,
              heroTag: heroTag,
              elevation: elevation,
              focusElevation: focusElevation,
              hoverElevation: hoverElevation,
              highlightElevation: highlightElevation,
              disabledElevation: disabledElevation,
              onPressed: onPressed,
              mouseCursor: mouseCursor,
              shape: shape,
              clipBehavior: clipBehavior,
              focusNode: focusNode,
              autofocus: autofocus,
              materialTapTargetSize: materialTapTargetSize,
              enableFeedback: enableFeedback,
            );
          },
        );

  BlockControlFAB.small({
    super.key,
    required super.currentStackTrace,
    required super.ownerClassInstance,
    required super.block,
    required super.actionType,
    super.navigate,
    //
    String? tooltip,
    Color? foregroundColor,
    Color? backgroundColor,
    Color? focusColor,
    Color? hoverColor,
    Color? splashColor,
    Object? heroTag,
    double? elevation,
    double? focusElevation,
    double? hoverElevation,
    double? highlightElevation,
    double? disabledElevation,
    required void Function()? onPressed,
    MouseCursor? mouseCursor,
    bool mini = false,
    ShapeBorder? shape,
    Clip clipBehavior = Clip.none,
    FocusNode? focusNode,
    bool autofocus = false,
    MaterialTapTargetSize? materialTapTargetSize,
    bool isExtended = false,
    bool? enableFeedback,
  }) : super(
          build: (VoidCallback? onPressed) {
            return FloatingActionButton.small(
              tooltip: tooltip,
              foregroundColor: foregroundColor,
              backgroundColor: backgroundColor,
              focusColor: focusColor,
              hoverColor: hoverColor,
              splashColor: splashColor,
              heroTag: heroTag,
              elevation: elevation,
              focusElevation: focusElevation,
              hoverElevation: hoverElevation,
              highlightElevation: highlightElevation,
              disabledElevation: disabledElevation,
              onPressed: onPressed,
              mouseCursor: mouseCursor,
              shape: shape,
              clipBehavior: clipBehavior,
              focusNode: focusNode,
              autofocus: autofocus,
              materialTapTargetSize: materialTapTargetSize,
              enableFeedback: enableFeedback,
            );
          },
        );
}
