targets:
  $default:
    builders:
      isar_generator:
        enabled: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - unused_element