name: flutter_artist
description: "Flutter Artist"
version: 0.0.1
homepage: https://o7planning.github.io
resolution: workspace


environment:
  sdk: ^3.6.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.12.1
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  flutter_form_builder: ^10.3.0+2
  tabbed_view: ^3.1.0
  equatable: ^2.0.8
  graphview: ^1.5.1
  flutter_breadcrumb: ^1.0.1
  uuid: ^4.5.1
  animated_tree_view: ^2.3.0
  hive: ^2.2.3
  multi_split_view: ^3.6.1
  flutter_advanced_switch: ^3.2.0
  web: ^1.1.1
  back_button_interceptor: ^8.0.4
  url_launcher: ^6.3.2

  flutter_artist_core: ^0.9.1
  flutter_artist_styles: ^0.9.1+1
  flutter_artist_styles_inspector: ^0.9.3+1
  flutter_artist_overlay_adapter: ^0.9.3
  flutter_artist_router: ^0.9.3
  flutter_artist_commons_ui: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

flutter:
  assets:
    - static-rs/