part of '../core.dart';

class _EventDispatcher {
  /// Broadcasts a system/storage-wide event generated by [StorageBackendAction]
  /// across all active shelves in the application infrastructure.
  static void broadcastSystemWideProjection({
    required ExecutionTrace executionTrace,
    required EventType eventType,
    required Block? eventBlock,
    required List<Type> events,
  }) {
    if (events.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#60000",
        shortDesc: "Events list is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }

    // StorageBackendAction contains domain-wide type changes without specific item IDs.
    // Thus, mainDataTypes is empty and all types are treated as extraDataTypes.
    final List<Type> mainDataTypes = const [];
    final List<Type> extraDataTypes = events;

    final _Storage storage = FlutterArtist.storage;

    for (String shelfName in storage._shelfMap.keys) {
      Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null) {
        continue;
      }
      Shelf? eventShelf = eventBlock?.shelf;

      // Skip internal shelf dispatch if explicit target eventBlock is provided.
      if (eventShelf != null && shelf == eventShelf) {
        continue;
      }

      for (Block block in shelf.blocks) {
        block._receiveEvent(
          executionTrace: executionTrace,
          mainDataTypes: mainDataTypes,
          extraDataTypes: extraDataTypes,
          eventSourceType: EventSourceType.external,
          requiresMaxSyncStrategy: true,
          syncStrategyOnFullQueryMode: BlockViewportSyncStrategy.nativeQuery,
          syncStrategyOnPageableQueryMode:
              BlockViewportSyncStrategy.effectedAndViewportItemIdsQuery,
          effectedItemIds: const [],
        );
      }

      // Dispatch to scalars.
      for (Scalar scalar in shelf.scalars) {
        // TODO: Implement scalar event reception when Scalar structure refactor is ready.
      }
    }
  }

  static void broadcastTargetedFootprint<ID extends Comparable>({
    required ExecutionTrace executionTrace,
    required EventType eventType,
    required Block? eventBlock,
    required List<Type> mainEvents,
    required List<ID> effectedItemIds,
    required List<Type> extraEvents,
  }) {
    if (mainEvents.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#25000",
        shortDesc: "Events list is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }
    if (effectedItemIds.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#25100",
        shortDesc: "effectedItemIds is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }

    final List<Type> mainDataTypes = mainEvents;
    final List<Type> extraDataTypes = extraEvents;

    final _Storage storage = FlutterArtist.storage;

    for (String shelfName in storage._shelfMap.keys) {
      Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null) {
        continue;
      }
      Shelf? eventShelf = eventBlock?.shelf;

      // Skip internal shelf dispatch if explicit target eventBlock is provided.
      if (eventShelf != null && shelf == eventShelf) {
        continue;
      }
      for (Block block in shelf.blocks) {
        block._receiveEvent(
          executionTrace: executionTrace,
          mainDataTypes: mainDataTypes,
          extraDataTypes: extraDataTypes,
          eventSourceType: EventSourceType.external,
          requiresMaxSyncStrategy: false,
          syncStrategyOnFullQueryMode: null,
          syncStrategyOnPageableQueryMode: null,
          effectedItemIds: effectedItemIds,
        );
      }

      // Dispatch to scalars.
      for (Scalar scalar in shelf.scalars) {
        // TODO: Implement scalar event reception when Scalar structure refactor is ready.
      }
    }
  }
}
