part of '../core.dart';

class _EventDispatcher {
  // ***************************************************************************
  // 1. SYSTEM-WIDE BROADCAST (StorageBackendAction)
  // ***************************************************************************

  /// Broadcasts a system/storage-wide event generated by [StorageBackendAction]
  /// across all active shelves in the application infrastructure.
  ///
  /// System-wide events carry no entity-specific IDs; thus observing blocks
  /// are automatically commanded to adopt the maximum viewport synchronization strategy.
  static void broadcastSystemWide({
    required EventType eventType,
    required List<Type> eventDataTypes,
  }) {
    final ExecutionTrace executionTrace =
        FlutterArtist.codeFlowLogger._createEventDispatcherExecutionTrace(
      ownerClassInstance: _EventDispatcher(),
      eventSourceType: EventSourceType.external,
    );

    executionTrace.addInfo(
      codeId: "#60000",
      shortDesc: "broadcastSystemWide()",
      parameters: {
        "eventType": eventType,
        "eventDataTypes": eventDataTypes,
      },
    );

    if (eventDataTypes.isEmpty) {
      executionTrace.addInfo(
        codeId: "#60100",
        shortDesc: "Event dataTypes is empty! --> Broadcast skipped.",
      );
      return;
    }

    final Set<Type> eventResolvedTypes =
        DataTypeEventUtils.getProjectionsDataTypes(eventDataTypes);
    final _Storage storage = FlutterArtist.storage;
    const EventSourceType externalEventSourceType = EventSourceType.external;

    for (final String shelfName in storage._shelfMap.keys) {
      final Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null) {
        continue;
      }

      // Dispatch to blocks across shelves (Dataset-level only)
      for (final Block block in shelf.blocks) {
        final Set<Type> listenerBlockReactionTypes = block
            .getResolvedReactionDataTypes(target: BlockReactionTarget.block);

        final bool isObserved = DataTypeEventUtils.hasIntersection(
          eventResolvedTypes,
          listenerBlockReactionTypes,
        );

        if (!isObserved) {
          continue;
        }

        // System-wide events enforce MAX Strategy across all observation boundaries
        block._receiveEventAtBlockLevel(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataKind: EventDataKind.main,
          eventDataTypes: eventDataTypes,
          syncStrategyOnFullQueryMode: BlockViewportSyncStrategy.nativeQuery,
          syncStrategyOnPageableQueryMode:
              BlockViewportSyncStrategy.effectedAndViewportItemIdsQuery,
          effectedItemIds: null,
        );
      }

      // Dispatch to scalars across shelves
      for (final Scalar scalar in shelf.scalars) {
        scalar._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataTypes: eventDataTypes,
        );
      }
    }
  }

  // ***************************************************************************
  // 2. EXTERNAL BROADCAST (Cross-Shelf Dispatch)
  // ***************************************************************************

  /// Broadcasts an external mutation event emitted from [eventBlock] to other observing
  /// blocks and scalars residing in DIFFERENT shelves across the application.
  static void broadcastExternal<ID extends Comparable>({
    required EventType eventType,
    required Block eventBlock,
    required List<Type> mainEvents,
    required List<ID> effectedItemIds,
    required List<Type> extraEvents,
  }) {
    final ExecutionTrace executionTrace =
        FlutterArtist.codeFlowLogger._createEventDispatcherExecutionTrace(
      ownerClassInstance: _EventDispatcher(),
      eventSourceType: EventSourceType.external,
    );

    executionTrace.addInfo(
      codeId: "#25000",
      shortDesc: "broadcastExternal()",
      parameters: {
        "eventType": eventType,
        "eventBlock": eventBlock,
        "mainEvents": mainEvents,
        "extraEvents": extraEvents,
        "effectedItemIds": effectedItemIds,
      },
    );

    if (mainEvents.isEmpty && extraEvents.isEmpty) {
      executionTrace.addInfo(
        codeId: "#25100",
        shortDesc: "Events list is empty! --> Broadcast skipped.",
      );
      return;
    }

    final List<Type> mainDataTypes = mainEvents;
    final List<Type> extraDataTypes = extraEvents;
    final List<Type> allDataTypes =
        {...mainDataTypes, ...extraDataTypes}.toList();

    final _Storage storage = FlutterArtist.storage;
    final Shelf eventShelf = eventBlock.shelf;
    const EventSourceType externalEventSourceType = EventSourceType.external;

    final Set<Type> eventMainResolvedTypes =
        DataTypeEventUtils.getProjectionsDataTypes(mainDataTypes);
    final Set<Type> eventExtraResolvedTypes =
        DataTypeEventUtils.getProjectionsDataTypes(extraDataTypes);

    for (final String shelfName in storage._shelfMap.keys) {
      final Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null || identical(shelf, eventShelf)) {
        continue; // Originating shelf is handled exclusively via broadcastInternal
      }

      // =======================================================================
      // 🚀 FAST DOMAIN BOUNDARY CHECK (Shelf-Level Isolation)
      // Verify if target shelf accepts events from the originating shelf
      // =======================================================================
      if (!shelf.canAcceptEventFrom(eventShelf)) {
        executionTrace.addInfo(
          codeId: "#25330",
          shortDesc:
              "Skipping ${getClassNameWithoutGenerics(shelf)}: Inbound reactionTags rejected source broadcastTags.",
          parameters: {
            "sourceBroadcastTags": eventShelf.effectiveConfig.broadcastTags,
            "targetReactionTags": shelf.effectiveConfig.reactionTags,
          },
        );
        continue;
      }

      executionTrace.addInfo(
        codeId: "#25340",
        shortDesc: "Broadcast Event to ${getClassNameWithoutGenerics(shelf)}.",
      );

      // =======================================================================
      // A. DISPATCH TO BLOCKS IN OTHER SHELVES
      // =======================================================================
      for (final Block block in shelf.blocks) {
        // A1. Item-Level Dispatch
        final Set<Type> currentItemReactionTypes =
            block.getResolvedReactionDataTypes(
                target: BlockReactionTarget.currentItem);

        final bool matchCurrentItem = DataTypeEventUtils.hasIntersection(
          eventMainResolvedTypes,
          currentItemReactionTypes,
        );

        if (matchCurrentItem && block.currentItem != null) {
          final bool isSameDomain =
              block.getItemType() == eventBlock.getItemType();
          final List<ID>? targetItemIds = isSameDomain ? effectedItemIds : null;

          block._receiveEventAtItemLevel(
            executionTrace: executionTrace,
            eventSourceType: externalEventSourceType,
            eventDataKind: EventDataKind.main,
            eventDataTypes: mainDataTypes,
            effectedItemIds: targetItemIds,
          );
        }

        // A2. Block-Level Dispatch
        final Set<Type> listenerTargetTypes = block.getDeclaredMainDataTypes();
        final Set<Type> listenerBlockReactionTypes = block
            .getResolvedReactionDataTypes(target: BlockReactionTarget.block);

        final BlockEventDispatchPlan<ID> plan =
            BlockEventDispatchPlanResolver.resolvePlan<ID>(
          eventMainResolvedTypes: eventMainResolvedTypes,
          eventExtraResolvedTypes: eventExtraResolvedTypes,
          sourceEffectedItemIds: effectedItemIds,
          listenerTargetTypes: listenerTargetTypes,
          listenerReactionTypes: listenerBlockReactionTypes,
        );

        if (!plan.shouldDispatch) {
          continue;
        }

        final BlockViewportSyncStrategy? syncStrategyOnFullQueryMode =
            plan.requiresMaxSyncStrategy
                ? BlockViewportSyncStrategy.nativeQuery
                : null;

        final BlockViewportSyncStrategy? syncStrategyOnPageableQueryMode =
            plan.requiresMaxSyncStrategy
                ? BlockViewportSyncStrategy.effectedAndViewportItemIdsQuery
                : null;

        // Dispatch main event batch
        block._receiveEventAtBlockLevel(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataKind: EventDataKind.main,
          eventDataTypes: mainDataTypes,
          syncStrategyOnFullQueryMode: syncStrategyOnFullQueryMode,
          syncStrategyOnPageableQueryMode: syncStrategyOnPageableQueryMode,
          effectedItemIds: plan.effectiveItemIds,
        );

        // Dispatch extra event batch if present
        if (extraDataTypes.isNotEmpty) {
          block._receiveEventAtBlockLevel(
            executionTrace: executionTrace,
            eventSourceType: externalEventSourceType,
            eventDataKind: EventDataKind.extra,
            eventDataTypes: extraDataTypes,
            syncStrategyOnFullQueryMode: syncStrategyOnFullQueryMode,
            syncStrategyOnPageableQueryMode: syncStrategyOnPageableQueryMode,
            effectedItemIds: null,
          );
        }
      }

      // =======================================================================
      // B. DISPATCH TO SCALARS IN OTHER SHELVES
      // =======================================================================
      for (final Scalar scalar in shelf.scalars) {
        scalar._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataTypes: allDataTypes,
        );
      }
    }
  }

  // ***************************************************************************
  // 3. INTERNAL BROADCAST (Within Same Shelf)
  // ***************************************************************************

  /// Dispatches an internal mutation event generated by [eventBlock] to other observing
  /// blocks and scalars residing within the same [Shelf].
  ///
  /// Self-reaction is fully permitted:
  /// - [BlockReactionTarget.currentItem] refreshes active item details.
  /// - [BlockReactionTarget.block] commands dataset invalidation/re-queries for the block itself.
  static void broadcastInternal<ID extends Comparable>({
    required EventType eventType,
    required Block eventBlock,
    required List<ID> effectedItemIds,
  }) {
    final ExecutionTrace executionTrace =
        FlutterArtist.codeFlowLogger._createEventDispatcherExecutionTrace(
      ownerClassInstance: _EventDispatcher(),
      eventSourceType: EventSourceType.internal,
    );

    executionTrace.addInfo(
      codeId: "#88000",
      shortDesc: "broadcastInternal()",
      parameters: {
        "eventType": eventType,
        "eventBlock": eventBlock,
        "effectedItemIds": effectedItemIds,
      },
    );

    // Resolve event data types emitted by the source block
    final List<Type> mainDataTypes =
        eventBlock.getDeclaredMainBroadcastDataTypes().toList();
    final List<Type> extraDataTypes =
        eventBlock.getDeclaredExtraBroadcastDataTypes().toList();
    final List<Type> allDataTypes =
        {...mainDataTypes, ...extraDataTypes}.toList();

    // Early exit if the source block emits no broadcastable data types
    if (allDataTypes.isEmpty) {
      executionTrace.addInfo(
        codeId: "#88100",
        shortDesc: "Broadcast types are empty! --> Broadcast skipped.",
      );
      return;
    }

    final Shelf shelf = eventBlock.shelf;

    executionTrace.addSeparator();

    const EventSourceType internalEventSourceType = EventSourceType.internal;

    // Resolve projection families for accurate type matching
    final Set<Type> eventMainResolvedTypes =
        eventBlock.getResolvedBroadcastDataTypes();
    final Set<Type> eventExtraResolvedTypes =
        DataTypeEventUtils.getProjectionsDataTypes(extraDataTypes);

    // =========================================================================
    // 1. DISPATCH TO BLOCKS IN THE SAME SHELF (INCLUDING eventBlock ITSELF)
    // =========================================================================
    for (final Block block in shelf.blocks) {
      final bool isSelf = identical(block, eventBlock);

      // -----------------------------------------------------------------------
      // A. ITEM-LEVEL DISPATCH (target: BlockReactionTarget.currentItem)
      // Dispatched to both Self and Peer/Parent blocks observing this entity.
      // -----------------------------------------------------------------------
      final Set<Type> currentItemReactionTypes =
          block.getResolvedReactionDataTypes(
              target: BlockReactionTarget.currentItem);

      final bool matchCurrentItem = DataTypeEventUtils.hasIntersection(
        eventMainResolvedTypes,
        currentItemReactionTypes,
      );

      if (matchCurrentItem && block.currentItem != null) {
        final bool isSameDomain =
            block.getItemType() == eventBlock.getItemType();
        final List<ID>? targetItemIds = isSameDomain ? effectedItemIds : null;

        executionTrace.addInfo(
          codeId: "#88600",
          shortDesc: isSelf
              ? "Self-dispatching to ${getClassNameWithoutGenerics(block)} for currentItem invalidation"
              : "Dispatching currentItem invalidation to ${getClassNameWithoutGenerics(block)}",
          parameters: {
            "eventSourceType": internalEventSourceType,
            "eventDataKind": EventDataKind.main,
            "eventDataTypes": mainDataTypes,
            "targetItemIds": targetItemIds,
          },
        );

        block._receiveEventAtItemLevel(
          executionTrace: executionTrace,
          eventSourceType: internalEventSourceType,
          eventDataKind: EventDataKind.main,
          eventDataTypes: mainDataTypes,
          effectedItemIds: targetItemIds,
        );
      }

      // -----------------------------------------------------------------------
      // B. BLOCK-LEVEL DISPATCH (target: BlockReactionTarget.block)
      // Unlocked for Self as well, supporting self re-query upon deletions/actions.
      // -----------------------------------------------------------------------
      final Set<Type> listenerTargetTypes =
          block.getDeclaredMainBroadcastDataTypes();
      final Set<Type> listenerBlockReactionTypes =
          block.getResolvedReactionDataTypes(target: BlockReactionTarget.block);

      final BlockEventDispatchPlan<ID> plan =
          BlockEventDispatchPlanResolver.resolvePlan<ID>(
        eventMainResolvedTypes: eventMainResolvedTypes,
        eventExtraResolvedTypes: eventExtraResolvedTypes,
        sourceEffectedItemIds: effectedItemIds,
        listenerTargetTypes: listenerTargetTypes,
        listenerReactionTypes: listenerBlockReactionTypes,
      );

      if (!plan.shouldDispatch) {
        continue;
      }

      final BlockViewportSyncStrategy? syncStrategyOnFullQueryMode =
          plan.requiresMaxSyncStrategy
              ? BlockViewportSyncStrategy.nativeQuery
              : null;

      final BlockViewportSyncStrategy? syncStrategyOnPageableQueryMode =
          plan.requiresMaxSyncStrategy
              ? BlockViewportSyncStrategy.effectedAndViewportItemIdsQuery
              : null;

      executionTrace.addNonControllableCall(
        codeId: "#88600",
        caller: block,
        methodName: "_receiveEventAtBlockLevel",
        suffixShortDesc: "",
        parameters: {
          "eventSourceType": internalEventSourceType,
          "eventDataKind": EventDataKind.main,
          "eventDataTypes": mainDataTypes,
          "syncStrategyOnFullQueryMode": syncStrategyOnFullQueryMode,
          "syncStrategyOnPageableQueryMode": syncStrategyOnPageableQueryMode,
          "effectedItemIds": plan.effectiveItemIds,
        },
      );

      block._receiveEventAtBlockLevel(
        executionTrace: executionTrace,
        eventSourceType: internalEventSourceType,
        eventDataKind: EventDataKind.main,
        eventDataTypes: mainDataTypes,
        syncStrategyOnFullQueryMode: syncStrategyOnFullQueryMode,
        syncStrategyOnPageableQueryMode: syncStrategyOnPageableQueryMode,
        effectedItemIds: plan.effectiveItemIds,
      );

      // Dispatch extra event batch if present
      if (extraDataTypes.isNotEmpty) {
        executionTrace.addNonControllableCall(
          codeId: "#88640",
          caller: block,
          methodName: "_receiveEventAtBlockLevel",
          suffixShortDesc: "(Extra)",
          parameters: {
            "eventSourceType": internalEventSourceType,
            "eventDataKind": EventDataKind.extra,
            "eventDataTypes": extraDataTypes,
            "syncStrategyOnFullQueryMode": syncStrategyOnFullQueryMode,
            "syncStrategyOnPageableQueryMode": syncStrategyOnPageableQueryMode,
            "effectedItemIds": null,
          },
        );

        block._receiveEventAtBlockLevel(
          executionTrace: executionTrace,
          eventSourceType: internalEventSourceType,
          eventDataKind: EventDataKind.extra,
          eventDataTypes: extraDataTypes,
          syncStrategyOnFullQueryMode: syncStrategyOnFullQueryMode,
          syncStrategyOnPageableQueryMode: syncStrategyOnPageableQueryMode,
          effectedItemIds: null,
        );
      }
    }

    // =========================================================================
    // 2. DISPATCH TO SCALARS IN THE SAME SHELF
    // =========================================================================
    for (final Scalar scalar in shelf.scalars) {
      executionTrace.addNonControllableCall(
        codeId: "#88700",
        caller: scalar,
        methodName: "_receiveEvent",
        suffixShortDesc: "",
        parameters: {
          "eventSourceType": internalEventSourceType,
          "dataTypes": allDataTypes,
        },
      );

      scalar._receiveEvent(
        executionTrace: executionTrace,
        eventSourceType: internalEventSourceType,
        eventDataTypes: allDataTypes,
      );
    }
  }
}
