part of '../core.dart';

class _EventDispatcher {
  /// Broadcasts a system/storage-wide event generated by [StorageBackendAction]
  /// across all active shelves in the application infrastructure.
  static void broadcastSystemWide({
    required EventType eventType,
    required List<Type> eventDataTypes,
  }) {
    ExecutionTrace executionTrace =
        FlutterArtist.codeFlowLogger._createEventDispatcherExecutionTrace(
      ownerClassInstance: _EventDispatcher(),
    );
    executionTrace._addTraceStep(
      codeId: "#60000",
      shortDesc: "broadcastSystemWideProjection()",
      parameters: {
        "eventType": eventType,
        "eventDataTypes": eventDataTypes,
      },
      traceStepType: TraceStepType.debug,
    );
    if (eventDataTypes.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#60100",
        shortDesc: "Event dataTypes is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }

    final _Storage storage = FlutterArtist.storage;

    for (String shelfName in storage._shelfMap.keys) {
      Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null) {
        continue;
      }
      for (Block block in shelf.blocks) {
        block._receiveSystemWideProjection(
          executionTrace: executionTrace,
          eventDataTypes: eventDataTypes,
          eventSourceType: EventSourceType.external,
        );
      }

      // Dispatch to scalars.
      for (Scalar scalar in shelf.scalars) {
        scalar._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: EventSourceType.external,
          eventDataTypes: eventDataTypes,
        );
      }
    }
  }

  static void broadcastExternal<ID extends Comparable>({
    required EventType eventType,
    required Block eventBlock,
    required List<Type> mainEvents,
    required List<ID> effectedItemIds,
    required List<Type> extraEvents,
  }) {
    ExecutionTrace executionTrace =
        FlutterArtist.codeFlowLogger._createEventDispatcherExecutionTrace(
      ownerClassInstance: _EventDispatcher(),
    );
    executionTrace._addTraceStep(
      codeId: "#25000",
      shortDesc: "broadcastTargetedFootprint()",
      parameters: {
        "eventType": eventType,
        "eventBlock": eventBlock,
        "mainEvents": mainEvents,
        "extraEvents": extraEvents,
        "effectedItemIds": effectedItemIds,
      },
      traceStepType: TraceStepType.debug,
    );
    //
    if (mainEvents.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#25100",
        shortDesc: "Events list is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }
    if (effectedItemIds.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#25200",
        shortDesc: "effectedItemIds is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }

    final List<Type> mainDataTypes = mainEvents;
    final List<Type> extraDataTypes = extraEvents;
    final List<Type> allDataType =
        {...mainDataTypes, ...extraDataTypes}.toList();

    final _Storage storage = FlutterArtist.storage;

    for (String shelfName in storage._shelfMap.keys) {
      Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null) {
        continue;
      }
      Shelf eventShelf = eventBlock.shelf;
      // Skip internal shelf dispatch if explicit target eventBlock is provided.
      if (shelf == eventShelf) {
        continue;
      }
      executionTrace._addTraceStep(
        codeId: "#25300",
        shortDesc: "Broadcast Event to ${getClassNameWithoutGenerics(shelf)}.",
        traceStepType: TraceStepType.separator,
      );
      executionTrace._addTraceStep(
        codeId: "#25340",
        shortDesc: "Broadcast Event to ${getClassNameWithoutGenerics(shelf)}.",
        traceStepType: TraceStepType.info,
      );
      final EventSourceType externalEventSourceType = EventSourceType.external;
      final bool requiresMaxSyncStrategy = false;
      // Dispatch to blocks.
      for (Block block in shelf.blocks) {
        executionTrace._addTraceStep(
          codeId: "#25600",
          shortDesc:
              "Calling ${getClassNameWithoutGenerics(block)}._receiveEvent()",
          parameters: {
            "eventSourceType": externalEventSourceType,
            "eventDataKind": EventDataKind.main,
            "eventDataTypes": mainDataTypes,
            "syncStrategyOnFullQueryMode": null,
            "syncStrategyOnPageableQueryMode": null,
            "effectedItemIds": effectedItemIds,
          },
          traceStepType: TraceStepType.nonControllableCalling,
        );
        block._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataKind: EventDataKind.main,
          eventDataTypes: mainDataTypes,
          syncStrategyOnFullQueryMode: null,
          syncStrategyOnPageableQueryMode: null,
          effectedItemIds: effectedItemIds,
        );
        if (extraDataTypes.isNotEmpty) {
          executionTrace._addTraceStep(
            codeId: "#25640",
            shortDesc:
                "Calling ${getClassNameWithoutGenerics(block)}._receiveEvent()",
            parameters: {
              "eventSourceType": externalEventSourceType,
              "eventDataKind": EventDataKind.extra,
              "eventDataTypes": extraDataTypes,
              "syncStrategyOnFullQueryMode": null,
              "syncStrategyOnPageableQueryMode": null,
              "effectedItemIds": null,
            },
            traceStepType: TraceStepType.nonControllableCalling,
          );
          block._receiveEvent(
            executionTrace: executionTrace,
            eventSourceType: externalEventSourceType,
            eventDataKind: EventDataKind.extra,
            eventDataTypes: extraDataTypes,
            syncStrategyOnFullQueryMode: null,
            syncStrategyOnPageableQueryMode: null,
            effectedItemIds: null,
          );
        }
      }
      // Dispatch to scalars.
      for (Scalar scalar in shelf.scalars) {
        executionTrace._addTraceStep(
          codeId: "#25700",
          shortDesc:
              "Calling ${getClassNameWithoutGenerics(scalar)}._receiveEvent()",
          parameters: {
            "eventSourceType": externalEventSourceType,
            "dataTypes": allDataType,
          },
          traceStepType: TraceStepType.nonControllableCalling,
        );
        scalar._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataTypes: allDataType,
        );
      }
    }
  }

  static void broadcastInternal<ID extends Comparable>({
    required EventType eventType,
    required Block eventBlock,
    required List<Type> mainEvents,
    required List<ID> effectedItemIds,
    required List<Type> extraEvents,
  }) {
    ExecutionTrace executionTrace =
        FlutterArtist.codeFlowLogger._createEventDispatcherExecutionTrace(
      ownerClassInstance: _EventDispatcher(),
    );
    executionTrace._addTraceStep(
      codeId: "#88000",
      shortDesc: "broadcastTargetedFootprint()",
      parameters: {
        "eventType": eventType,
        "eventBlock": eventBlock,
        "mainEvents": mainEvents,
        "extraEvents": extraEvents,
        "effectedItemIds": effectedItemIds,
      },
      traceStepType: TraceStepType.debug,
    );
    //
    if (mainEvents.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#88100",
        shortDesc: "Events list is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }
    if (effectedItemIds.isEmpty) {
      executionTrace._addTraceStep(
        codeId: "#25200",
        shortDesc: "effectedItemIds is empty! --> Broadcast skipped.",
        traceStepType: TraceStepType.eventInfo,
      );
      return;
    }

    final List<Type> mainDataTypes = mainEvents;
    final List<Type> extraDataTypes = extraEvents;
    final List<Type> allDataType =
        {...mainDataTypes, ...extraDataTypes}.toList();

    final _Storage storage = FlutterArtist.storage;

    for (String shelfName in storage._shelfMap.keys) {
      Shelf? shelf = storage.findShelfByName(shelfName);
      if (shelf == null) {
        continue;
      }
      Shelf eventShelf = eventBlock.shelf;
      // Skip internal shelf dispatch if explicit target eventBlock is provided.
      if (shelf == eventShelf) {
        continue;
      }
      executionTrace._addTraceStep(
        codeId: "#25300",
        shortDesc: "Broadcast Event to ${getClassNameWithoutGenerics(shelf)}.",
        traceStepType: TraceStepType.separator,
      );
      executionTrace._addTraceStep(
        codeId: "#25340",
        shortDesc: "Broadcast Event to ${getClassNameWithoutGenerics(shelf)}.",
        traceStepType: TraceStepType.info,
      );
      final EventSourceType externalEventSourceType = EventSourceType.external;
      final bool requiresMaxSyncStrategy = false;
      // Dispatch to blocks.
      for (Block block in shelf.blocks) {
        executionTrace._addTraceStep(
          codeId: "#25600",
          shortDesc:
              "Calling ${getClassNameWithoutGenerics(block)}._receiveEvent()",
          parameters: {
            "eventSourceType": externalEventSourceType,
            "eventDataKind": EventDataKind.main,
            "eventDataTypes": mainDataTypes,
            "syncStrategyOnFullQueryMode": null,
            "syncStrategyOnPageableQueryMode": null,
            "effectedItemIds": effectedItemIds,
          },
          traceStepType: TraceStepType.nonControllableCalling,
        );
        block._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataKind: EventDataKind.main,
          eventDataTypes: mainDataTypes,
          syncStrategyOnFullQueryMode: null,
          syncStrategyOnPageableQueryMode: null,
          effectedItemIds: effectedItemIds,
        );
        if (extraDataTypes.isNotEmpty) {
          executionTrace._addTraceStep(
            codeId: "#25640",
            shortDesc:
                "Calling ${getClassNameWithoutGenerics(block)}._receiveEvent()",
            parameters: {
              "eventSourceType": externalEventSourceType,
              "eventDataKind": EventDataKind.extra,
              "eventDataTypes": extraDataTypes,
              "syncStrategyOnFullQueryMode": null,
              "syncStrategyOnPageableQueryMode": null,
              "effectedItemIds": null,
            },
            traceStepType: TraceStepType.nonControllableCalling,
          );
          block._receiveEvent(
            executionTrace: executionTrace,
            eventSourceType: externalEventSourceType,
            eventDataKind: EventDataKind.extra,
            eventDataTypes: extraDataTypes,
            syncStrategyOnFullQueryMode: null,
            syncStrategyOnPageableQueryMode: null,
            effectedItemIds: null,
          );
        }
      }
      // Dispatch to scalars.
      for (Scalar scalar in shelf.scalars) {
        executionTrace._addTraceStep(
          codeId: "#25700",
          shortDesc:
              "Calling ${getClassNameWithoutGenerics(scalar)}._receiveEvent()",
          parameters: {
            "eventSourceType": externalEventSourceType,
            "dataTypes": allDataType,
          },
          traceStepType: TraceStepType.nonControllableCalling,
        );
        scalar._receiveEvent(
          executionTrace: executionTrace,
          eventSourceType: externalEventSourceType,
          eventDataTypes: allDataType,
        );
      }
    }
  }
}
