enum TaskType {
  shelfQuery,
  shelfInternalReact,
  //
  blockClearCurrentItem,
  blockDeleteItem,
  blockDeleteItems,
  blockPrepareToCreateItem,
  blockQuery,
  blockSilentAction,
  blockQuickChildBlockItems,
  blockQuickCreateItem,
  blockSilentCreateItem,
  blockQuickCreateMultiItems,
  blockQuickUpdateItem,
  blockSilentUpdateItem,
  blockSelectItemAsCurrent,
  blockClearance,
  //
  filterModelLoadData,
  filterModelFilterPanelChanged,
  //
  formModelEnterFormFields,
  formModelLoadData,
  formModelSaveForm,
  formModelFormViewChanged,
  //
  scalarQuery,
  scalarClearance,
  scalarSilentAction;
}
