enum TaskType {
  shelfQuery,
  //
  blockClearCurrentItem,
  blockDeleteItem,
  blockDeleteItems,
  blockPrepareToCreateItem,
  blockQuery,
  blockQuickAction,
  blockQuickChildBlockItems,
  blockQuickCreateItem,
  blockQuickCreateMultiItems,
  blockQuickUpdateItem,
  blockSelectItemAsCurrent,
  //
  filterModelFilterViewChanged,
  //
  formModelEnterFormFields,
  formModelLoadForm,
  formModelSaveForm,
  formModelFormViewChanged,
  //
  scalarQuery,
  scalarQuickAction;
}
