enum XShelfType {
  naturalQuery,
  blockQuery,
  blockQueryEmpty,
  blockQueryAndPrepareToCreate,
  blockPrepareFormToCreateItem,
  blockCurrItemClearance,
  blockClearance,
  blockItemDeletion,
  blockMultiItemsDeletion,
  blockCurrItemSelection,
  blockQuickActionExecution,
  blockQuickItemCreation,
  blockSilentItemCreation,
  blockQuickItemUpdate,
  blockSilentItemUpdate,
  blockQuickMultiItemsCreation,
  @Deprecated("Xoa di")
  blockQuickChildBlockItemsAction,
  //
  shelfExternalReaction,
  //
  filterModelQueryAll,
  formModelSave,
  formModelEnterFields,
  formViewChange,
  filterViewChange,
  //
  scalarQuery,
  scalarClearance,
  scalarSilentAction,
  scalarQuickExtraDataLoadAction;
}
