enum XShelfType {
  naturalQuery,
  blockQuery,
  blockQueryEmpty,
  blockQueryAndPrepareToCreate,
  blockQueryAndPrepareToEdit,
  blockPrepareFormToCreateItem,
  blockCurrItemClearance,
  blockClearance,
  blockItemDeletion,
  blockMultiItemsDeletion,
  blockCurrItemSelection,
  blockSilentActionExecution,
  blockQuickItemCreation,
  blockSilentItemCreation,
  blockQuickItemUpdate,
  blockSilentItemUpdate,
  blockQuickMultiItemsCreation,
  //
  shelfExternalReaction,
  //
  filterModelQuery,
  formModelSave,
  formModelEnterFields,
  formViewChange,
  filterPanelChange,
  //
  scalarQuery,
  scalarClearance,
  scalarSilentAction,
  scalarQuickExtraDataLoadAction;
}
