enum XShelfType {
  naturalQuery,
  blockQuery,
  blockQueryEmpty,
  blockQueryAndPrepareToCreate,
  blockQueryAndPrepareToEdit,
  blockPrepareFormToCreateItem,
  blockCurrItemClear,
  blockClearItems,
  blockItemDeletion,
  blockMultiItemDeletion,
  blockCurrItemSelection,
  blockBackendActionExecution,
  blockQuickItemCreation,
  blockQuickItemUpdate,
  //
  shelfExternalReaction,
  //
  filterModelQuery,
  formModelSave,
  formModelEnterFields,
  formViewChange,
  filterPanelChange,
  //
  scalarQuery,
  scalarClear,
  scalarBackendAction,
  scalarQuickExtraDataLoadAction;
}
